# Generated by Django 4.2.7 on 2025-01-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_gallery",
                    models.CharField(
                        max_length=255, verbose_name="Заголовок для галереи"
                    ),
                ),
                (
                    "title_gallery_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок для галереи"
                    ),
                ),
                (
                    "title_gallery_ky",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Заголовок для галереи"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(upload_to="base/", verbose_name="Фотография"),
                ),
            ],
            options={
                "verbose_name": "Галерея",
                "verbose_name_plural": "Галереи",
            },
        ),
        migrations.CreateModel(
            name="We_Invite_To_View",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Мы предлагаем к просмотру"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Мы предлагаем к просмотру",
                    ),
                ),
                (
                    "title_ky",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Мы предлагаем к просмотру",
                    ),
                ),
                (
                    "title_place",
                    models.CharField(
                        max_length=255, verbose_name="Заголовок для места просмотра"
                    ),
                ),
                (
                    "title_place_ru",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Заголовок для места просмотра",
                    ),
                ),
                (
                    "title_place_ky",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Заголовок для места просмотра",
                    ),
                ),
                (
                    "description_place",
                    models.CharField(
                        max_length=255, verbose_name="Описание для места просмотра"
                    ),
                ),
                (
                    "description_place_ru",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Описание для места просмотра",
                    ),
                ),
                (
                    "description_place_ky",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Описание для места просмотра",
                    ),
                ),
                ("date_place", models.DateField(verbose_name="Дата места просмотра")),
                (
                    "image_place",
                    models.ImageField(
                        upload_to="base/",
                        verbose_name="Изображение для места просмотра",
                    ),
                ),
            ],
            options={
                "verbose_name": "Места для просмотра",
                "verbose_name_plural": "Места для просмотра",
            },
        ),
    ]
