# Generated by Django 4.2.7 on 2025-01-30 16:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_media', models.CharField(max_length=100, verbose_name='Заголовок СМИ страницы "Новости"')),
                ('title_media_ru', models.CharField(max_length=100, null=True, verbose_name='Заголовок СМИ страницы "Новости"')),
                ('title_media_ky', models.CharField(max_length=100, null=True, verbose_name='Заголовок СМИ страницы "Новости"')),
                ('description_media', models.TextField(verbose_name='Описание СМИ страницы "Новости"')),
                ('description_media_ru', models.TextField(null=True, verbose_name='Описание СМИ страницы "Новости"')),
                ('description_media_ky', models.TextField(null=True, verbose_name='Описание СМИ страницы "Новости"')),
                ('date_media', models.DateTimeField(verbose_name='Дата СМИ страницы "Новости"')),
                ('image_media', models.ImageField(upload_to='news/')),
            ],
            options={
                'verbose_name': 'СМИ',
                'verbose_name_plural': 'СМИ',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_news', models.CharField(max_length=100, verbose_name='Заголовок новостей страницы "Новости"')),
                ('title_news_ru', models.CharField(max_length=100, null=True, verbose_name='Заголовок новостей страницы "Новости"')),
                ('title_news_ky', models.CharField(max_length=100, null=True, verbose_name='Заголовок новостей страницы "Новости"')),
                ('description_news', models.TextField(verbose_name='Описание новостей страницы "Новости"')),
                ('description_news_ru', models.TextField(null=True, verbose_name='Описание новостей страницы "Новости"')),
                ('description_news_ky', models.TextField(null=True, verbose_name='Описание новостей страницы "Новости"')),
                ('date_news', models.DateTimeField(verbose_name='Дата новостей страницы "Новости"')),
                ('image_news', models.ImageField(upload_to='news/')),
                ('first_paragraph', models.TextField(verbose_name='Первый абзац детальный просмотр новостей страницы "Новости"')),
                ('first_paragraph_ru', models.TextField(null=True, verbose_name='Первый абзац детальный просмотр новостей страницы "Новости"')),
                ('first_paragraph_ky', models.TextField(null=True, verbose_name='Первый абзац детальный просмотр новостей страницы "Новости"')),
                ('second_paragraph', models.TextField(verbose_name='Второй абзац детальный просмотр новостей страницы "Новости"')),
                ('second_paragraph_ru', models.TextField(null=True, verbose_name='Второй абзац детальный просмотр новостей страницы "Новости"')),
                ('second_paragraph_ky', models.TextField(null=True, verbose_name='Второй абзац детальный просмотр новостей страницы "Новости"')),
                ('general_paragraph', ckeditor.fields.RichTextField(verbose_name='Общий абзац детальный просмотр новостей страницы "Новости"')),
                ('general_paragraph_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Общий абзац детальный просмотр новостей страницы "Новости"')),
                ('general_paragraph_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Общий абзац детальный просмотр новостей страницы "Новости"')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
