# Generated by Django 4.2.7 on 2025-02-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passport", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(verbose_name="Заголовок вакансии")),
                (
                    "title_ru",
                    models.TextField(null=True, verbose_name="Заголовок вакансии"),
                ),
                (
                    "title_ky",
                    models.TextField(null=True, verbose_name="Заголовок вакансии"),
                ),
                ("description", models.TextField(verbose_name="Описание вакансий")),
                (
                    "description_ru",
                    models.TextField(null=True, verbose_name="Описание вакансий"),
                ),
                (
                    "description_ky",
                    models.TextField(null=True, verbose_name="Описание вакансий"),
                ),
            ],
            options={
                "verbose_name": "",
                "verbose_name_plural": "",
            },
        ),
    ]
