# Generated by Django 4.2.7 on 2025-02-01 11:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("passport", "0002_vacancy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vacancy",
            options={"verbose_name": "", "verbose_name_plural": "Вакансия"},
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="description",
            field=ckeditor.fields.RichTextField(verbose_name="Описание вакансий"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="description_ky",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание вакансий"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="description_ru",
            field=ckeditor.fields.RichTextField(
                null=True, verbose_name="Описание вакансий"
            ),
        ),
    ]
